### PR TITLE
Latest ray raygui

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by adct-the-experimenter** [comment]
Wow! Thank you for the effort. Thank you for using 3d Audio Producer. I will test this and merge if the test is successful.

**Comment by KOLANICH** [comment]
>I will test this and merge if the test is successful.

For me it doesn't work. The widget for choosing a file seems to be broken IDK why, as you see I have mostly updated the libs to match the latest version of `raylib` (I just cloned its repo, build its packages and installed them) installed in my system + addressed the changes in it (though I'm not sure that I had addressed them the right way, I don't use raylib myself)

**Comment by adct-the-experimenter** [comment]
@KOLANICH I was able to fix the file dialog widget and test the program.

In main_gui_editor.cpp and sound_bank.cpp 

fileDialogState.windowBounds = {200, 200};

should be changed to

fileDialogState.windowBounds = {200, 200, 440, 310};

Make this change and pull the 2 commits from master branch of my fork, then, I will make the pull request. 
Thank you for fixing some mistakes that I made.

**Comment by adct-the-experimenter** [comment]
Merged.

**Comment by KOLANICH** [comment]
There is a problem though. For me it doesn't work. I mean the speakers are surely activated (I hear a very slight click in headphones) and I see in PipeWire graph this app is connected, but when I click "Play" I hear nothing and I cannot edit the timeline. But I'm not ready now to dive deep to fix that.

**Comment by adct-the-experimenter** [comment]
@KOLANICH Create an issue. I can help you in the Github issues section. 
It could be that a start playback marker is missing in Timeline which makes audio play.

**Pull request merged**
